### ISSUE TITLE
Email Validator

### ISSUE THREAD

**Issue by nischal619** [nischal619/paithan#1]
create a email validator in email_validator.py file
this program will check if the input email is valid of not
just check if the user entered email has '@' and '.' sign or not

**Comment by whyrass** [comment]
I'd like to work on it

**Comment by Montekkundan** [comment]
@nischal619 Hi can you assign this to me! 😄

**Comment by codemii** [comment]
Hi @nischal619 , I would like to work on this.

**Comment by nischalkhanal205** [comment]
assignthis to me
