### ISSUE TITLE
Capitalize string

### ISSUE THREAD

**Issue by nischal619** [nischal619/paithan#6]
Capitalizes the first letter of a string.

Create it in capitalize_string.py file

Resource:
https://www.30secondsofcode.org/python/s/capitalize

**Comment by sarthak17jain** [comment]
Please assign me this issue.

**Comment by kartikjoshi267** [comment]
Hey @nischal619 
Please check I have created a PR.

**Comment by nischalkhanal205** [comment]
assign me
